sudo: required

services:
  - docker

language: ruby
rvm:
  - 2.0

branches:
  only:
    - master

install:
  - make test-deps

script:
  - set -e
  - make build
  - make test
  - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    make upload;
    fi
  - set +e
